# Generated by Django 2.1 on 2018-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Test_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='results',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='values',
            field=models.TextField(default='{}'),
        ),
    ]
