# Generated by Django 2.1 on 2018-09-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLC_Test_App', '0002_auto_20180905_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(default='[]')),
            ],
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='results',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='values',
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLC_Test_App.TestCase'),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='test_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLC_Test_App.TestCaseInput'),
        ),
        migrations.AddField(
            model_name='testcaseinput',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLC_Test_App.TestCase'),
        ),
    ]
